name: Publish CublexCore to Maven Central

on:
  push:
    tags:
      - 'v*'  # Only if the pushed tag starts with v. Like v2.0.0

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Debug secrets
        run: |
          echo "USERNAME=$OSSRH_USERNAME"
          echo "PASSWORD=${#OSSRH_PASSWORD}"
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Publish to Sonatype
        run: ./gradlew publish
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_OWNERTRUST: ${{ secrets.GPG_OWNERTRUST }}


